---
ntp_prerequisites:
  - "{{ 'ntpsec' if ansible_facts['distribution_major_version'] | int >= 13 else 'ntp' }}"

ntp_name: "{{ 'ntpsec' if ansible_facts['distribution_major_version'] | int >= 13 else 'ntp' }}"
