---
common_zsh_source: "https://github.com/robbyrussell/oh-my-zsh.git"

common_minimal_apps:
  - bzip2
  - ca-certificates
  - fzf
  - git
  - gzip
  - htop
  - lsof
  - mtr
  - net-tools
  - ncdu
  - parted
  - plocate
  - rsync
  - screen
  - time
  - tree
  - unzip
  - vim
  - wget
  - zsh

common_optional_apps:
  - mc
  - powertop
